/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

/*
 * Add the java and kotlin src dirs leading to main
 * 
 * This will be where the files are kept for compilation and testing 
 */
sourceSets.main {
    java.srcDirs("\${dropProject.maven.repository}")
}

//NEW: Added gradle repository for tooling api
repositories {
    mavenCentral()
    mavenLocal()
}

//NEW: Added kotlin plugin for compile and testing
plugins {
    idea
    war
    java
    application
    id("org.springframework.boot") version "2.6.7"
    id("org.jetbrains.kotlin.jvm") version "1.5.31"
}

dependencies {
    implementation("org.springframework:spring-core:4.3.2.RELEASE") //Added new Spring implementation for Gradle
    implementation("org.springframework.amqp:spring-rabbit:1.5.2.RELEASE") //Added new Spring implementation for Gradle
    implementation("org.gradle:gradle-tooling-api:7.3-20210825160000+0000") //Added tooling api implementation
    runtimeOnly("org.slf4j:slf4j-simple:1.7.10") //NEW: Added runtime only implementation for tooling api (Should work)
}

group = "org.dropProject"
version = "0.9.6"
description = "DropProject"
java.sourceCompatibility = JavaVersion.VERSION_11

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}